import { signInWithGoogle, supabase } from "./supabase.js";
const APP_URL="https://derkitoo.github.io/promptnest/",$=(selector)=>document.querySelector(selector);let activePage={title:"",url:"",selection:""};
function show(name){["loading","signedOut","capture"].forEach(id=>$(`#${id}`).classList.toggle("hidden",id!==name))}
function message(text,type="error"){const box=$("#message");box.textContent=text;box.className=`message ${type}`}
async function capturePage(){const[tab]=await chrome.tabs.query({active:true,currentWindow:true});activePage.title=tab?.title||"Page sans titre";activePage.url=tab?.url||"";if(tab?.id&&/^https?:/i.test(activePage.url)){try{const[{result}]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>window.getSelection()?.toString().trim()||""});activePage.selection=result||""}catch{activePage.selection=""}}const stored=await chrome.storage.local.get("promptnest.pendingCapture"),pending=stored["promptnest.pendingCapture"];if(pending){activePage={...activePage,...pending};await chrome.storage.local.remove("promptnest.pendingCapture")}$("#pageTitle").textContent=activePage.title;$("#pageUrl").textContent=activePage.url||"Page protégée par Chrome";$("#title").value=activePage.title;if(activePage.selection){$("#content").value=activePage.selection;$("#selection").textContent=activePage.selection;$("#selectionWrap").classList.remove("hidden")}}
async function displaySession(session){if(!session)return show("signedOut");const user=session.user;$("#accountEmail").textContent=user.email||"";$("#accountName").textContent=user.user_metadata?.full_name||"Compte Google";$("#avatar").textContent=(user.user_metadata?.full_name||user.email||"P")[0].toUpperCase();show("capture");await capturePage()}
async function init(){show("loading");const{data,error}=await supabase.auth.getSession();if(error)return show("signedOut");await displaySession(data.session)}
$("#signIn").addEventListener("click",async()=>{const button=$("#signIn");button.disabled=true;button.textContent="Connexion…";try{await displaySession(await signInWithGoogle())}catch(error){show("signedOut");alert(error.message||"Connexion impossible.")}finally{button.disabled=false;button.innerHTML="<b>G</b> Continuer avec Google"}});
$("#signOut").addEventListener("click",async()=>{await supabase.auth.signOut();show("signedOut")});$("#openApp").addEventListener("click",()=>chrome.tabs.create({url:APP_URL}));$("#viewPrompts").addEventListener("click",()=>chrome.tabs.create({url:APP_URL}));
$("#captureForm").addEventListener("submit",async event=>{event.preventDefault();const button=$("#save");button.disabled=true;button.textContent="Enregistrement…";$("#message").classList.add("hidden");try{const{data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)throw new Error("Votre session a expiré. Reconnectez-vous.");const now=new Date().toISOString(),row={user_id:user.id,title:$("#title").value.trim(),content:$("#content").value.trim(),category_name:$("#category").value,tags:["capture-web"],source_url:activePage.url||null,page_title:activePage.title||null,selected_text:activePage.selection||null,personal_note:$("#note").value.trim()||null,updated_at:now,client_updated_at:now};const{error}=await supabase.from("prompts").insert(row);if(error)throw error;message("Prompt enregistré et synchronisé ✓","success");$("#note").value=""}catch(error){message(error.message||"Enregistrement impossible.")}finally{button.disabled=false;button.textContent="Enregistrer dans PromptNest"}});init();
